timezone = "local"

auto_sync = false
update_check = false
enter_accept = true
style = "auto"
ctrl_n_shortcuts = true

[dotfiles]
enabled = false

[sync]
records = false

[daemon]
enabled = false

[theme]
name = "catppuccin-mocha"

[stats]
common_subcommands = ["g", "git", "uv", "go", "odin", "kubectl"]
common_prefix = ["sudo"]
history_filter = [
  "^exit"
]
